before_script:  
 - set ANDROID_SDK_ROOT = "D:\Android\sdk"

stages:
  - test
  - build

test:
  stage: test
  script:
    - cd android
    - ./gradlew app:assembleDebug 
build:
  stage: build
  script:
    - ./flutter build apk