before_script:  
 - export ANDROID_HOME="D:\Android\sdk"
 - export PATH="D:\flutter\bin"
 - chmod a+x ./gradlew
 - gem install bundler
 - bundle install

dev:
    script:
     - flutter build apk --release
     - cd android
     - bundle exec fastlane 