before_script:  
 - export ANDROID_HOME="D:\Android\sdk"
 - export PATH="D:\flutter\bin"
 - chmod a+x ./gradlew

stages:
    - build

dev:
    stage: build
    script:
     - cd android
     - ./gradlew assembleDubg