before_script:  
 - export ANDROID_HOME="/home/luckyxmobile/Android/Sdk"
 - chmod a+x ./android
stages:
    - build

dev:
   stage: build
   script:
     - cd android
     - ./gradlew android:assembleDebug
