before_script:  
 - set ANDROID_SDK_ROOT = "D:\Android\sdk"
 - set-executionpolicy -executionpolicy unrestricted

dev:
    script:
     - chcp 65001
     - $ErrorActionPreference = "Stop"
     - flutter build apk --release
