test app:
  image: kattwinkel/flutter-android
  stage: test
  script:
  - cd app
  - flutter test
 
build app:
  image: kattwinkel/flutter-android
  stage: build
  script:
    - cd app
    - flutter build apk
  artifacts:
    expire_in: 1 week
    paths:
    - app/build/app/outputs/apk/release/app-release.apk