before_script:  
 - export ANDROID_HOME="/home/luckyxmobile/Android/Sdk"
 - chmod a+x ./gradlew

stages:
    - build

dev:
   stage: build
   script:
     - cd ./android
     - ./gradlew app:assembleDebug 
