before_script:
  # 解决中文乱码问题
  - chcp 936
stages:
    - build
dev:
   stage: build
   script:
     - flutter packages get
     - flutter test --coverage
     - genhtml -o coverage coverage/lcov.info
     - flutter build aot
