before_script:  
 - export PATH=`pwd`/flutter/bin:$PATH
 - chmod a+r /home/flutter/bin/cache/lockfile
 - chmod a+x ./android/gradlew
 
stages:
    - build

dev:
   stage: build
   script:
     - cd android
     - gradlew app:assembleDebug
